## Python Function

In [1]:
a = 3

In [3]:
print(dir(3))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [4]:
import sys

In [5]:
sys

<module 'sys' (built-in)>

In [6]:
print(dir(sys))

['__displayhook__', '__doc__', '__excepthook__', '__interactivehook__', '__loader__', '__name__', '__package__', '__spec__', '__stderr__', '__stdin__', '__stdout__', '_clear_type_cache', '_current_frames', '_debugmallocstats', '_getframe', '_git', '_home', '_xoptions', 'abiflags', 'api_version', 'argv', 'base_exec_prefix', 'base_prefix', 'builtin_module_names', 'byteorder', 'call_tracing', 'callstats', 'copyright', 'displayhook', 'dont_write_bytecode', 'exc_info', 'excepthook', 'exec_prefix', 'executable', 'exit', 'flags', 'float_info', 'float_repr_style', 'get_asyncgen_hooks', 'get_coroutine_wrapper', 'getallocatedblocks', 'getcheckinterval', 'getdefaultencoding', 'getdlopenflags', 'getfilesystemencodeerrors', 'getfilesystemencoding', 'getprofile', 'getrecursionlimit', 'getrefcount', 'getsizeof', 'getswitchinterval', 'gettrace', 'hash_info', 'hexversion', 'implementation', 'int_info', 'intern', 'is_finalizing', 'maxsize', 'maxunicode', 'meta_path', 'modules', 'path', 'path_hooks', 'pa

In [7]:
help(sys.exit)

Help on built-in function exit in module sys:

exit(...)
    exit([status])
    
    Exit the interpreter by raising SystemExit(status).
    If the status is omitted or None, it defaults to zero (i.e., success).
    If the status is an integer, it will be used as the system exit status.
    If it is another kind of object, it will be printed and the system
    exit status will be one (i.e., failure).



In [8]:
?sys.exit

In [9]:
l = [1,2,3,4,5]

In [10]:
print(dir(l))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [11]:
?l.append

In [12]:
l.append(2)
l

[1, 2, 3, 4, 5, 2]

In [13]:
?l.count

In [14]:
l.count(2)

2

## Function

In [15]:
def say_hello():
    print("hello world")

In [16]:
say_hello()

hello world


In [17]:
def say_hello(customer_name):
    print(f"Hello {customer_name}")

In [18]:
say_hello('David')

Hello David


In [19]:
def addNum(a,b):
    return a + b

In [20]:
addNum(2,3)

5

In [21]:
addNum('Hello','World')

'HelloWorld'

In [22]:
addNum('Hello',2)

TypeError: must be str, not int

In [23]:
def addNum2(a,b):
    return a + b * 3

In [24]:
addNum2(2,3)

11

In [25]:
addNum2(b = 2,a = 3)

9

In [26]:
def addall(x, *args):
    print(x)
    print(args)
    res = x
    for y in args:
        res += y
    return(res)

addall(1,2,3,4,5)

1
(2, 3, 4, 5)


15

In [27]:
def make_two_lists(**kwargs):
    print(kwargs)
    keys,values = [],[]
    for k,v in kwargs.items():
        keys.append(k)
        values.append(v)
    return([keys,values])

make_two_lists(david='M', Mary = 'F', John='M')

{'david': 'M', 'Mary': 'F', 'John': 'M'}


[['david', 'Mary', 'John'], ['M', 'F', 'M']]

In [28]:
d = {'david': 'M', 'Mary': 'F', 'John': 'M'}
d.items()

dict_items([('david', 'M'), ('Mary', 'F'), ('John', 'M')])

In [29]:
def addall(*args,x):
    print(x)
    print(args)
    res = x
    for y in args:
        res += y
    return(res)

addall(1,2,3,4,5)

TypeError: addall() missing 1 required keyword-only argument: 'x'

In [30]:
sum([1,2,3,4,5])

15

In [32]:
def s(*args):
    s2 = 0
    for y in args:
        s2 += y
    return s2

s(1,2,3,4,5,6,7)
s(1,2,3,4,5,6,7,8,9,10)

55

## Lambda

In [33]:
def square(num):
    result = num**2
    return(result) 

square(2)

4

In [34]:
def square(num):
    return num**2

square(2)

4

In [35]:
def square(num): return num ** 2

square(2)

4

In [36]:
lambda num: num ** 2

<function __main__.<lambda>>

In [37]:
square = lambda num: num ** 2

square(2)

4

In [39]:
def even(x):
    return x % 2 == 0

even(3)

False

In [40]:
even = lambda x: x%2==0

even(3)

False

In [41]:
def first(x):
    return x[0]

first('hello')

'h'

In [42]:
first = lambda s: s[0] 

first('hello')

'h'

In [43]:
def rev(s):
    return s[::-1]

rev('hello')

'olleh'

In [45]:
rev = lambda s: s[::-1]
rev('world')

'dlrow'

In [46]:
def adder(x, y):
    return x + y

adder(2,3)

5

In [47]:
adder =  lambda x,y : x+y

adder(3,4)

7

In [48]:
f = lambda x:x**2  # x is local

In [52]:
name = 'This is a global name'

In [53]:
def greet():
    # Enclosing function
    name = 'Sammy'  # Enclosing function locals
    def hello():
        print('Hello '+name )
    hello()
    
greet()

Hello This is a global name


In [51]:
print(name)

This is a global name


In [54]:
sum

<function sum>

In [55]:
david

NameError: name 'david' is not defined

In [56]:
len

<function len>

In [57]:
sum(range(1,101))

5050

In [58]:
sum = 0
for i in range(1,101):
    sum += i
sum

5050

In [59]:
sum(range(1,101))

TypeError: 'int' object is not callable

In [60]:
type(sum)

int

In [61]:
del sum

In [62]:
type(sum)

builtin_function_or_method

In [63]:
x = 50

def func(x):
    print('x is', x)
    x=2
    print('Changed local x to', x )

func(x)
print('x is still', x)

x is 50
Changed local x to 2
x is still 50


In [64]:
x = 50

def func():
    global x
    print('This function is now using the global x!' ) 
    print('Because of global x is: ', x)
    x=2
    print('Ran func(), changed global x to', x )
    
print('Before calling func(), x is: ', x)
func()
print('Value of x (outside of func()) is: ', x )

Before calling func(), x is:  50
This function is now using the global x!
Because of global x is:  50
Ran func(), changed global x to 2
Value of x (outside of func()) is:  2


## Error And Exception

In [65]:
try:
    f = open('testfile','w') 
    f.write('Test write this')
except IOError: #處理IOError
    print("Error: Could not find file or read data")
else:
    print("Content written succesfully")
f.close()

Content written succesfully


In [66]:
try:
    f = open('testfile','r') 
    f.write('Test write this')
except IOError: #處理IOError
    print("Error: Could not find file or read data")
else:
    print("Content written succesfully")
f.close()

Error: Could not find file or read data


In [69]:
dividend = input("Dividend: ")
divisor = input("Divisor: ") 
print(float(dividend) / float(divisor))  

Dividend: 3
Divisor: 0


ZeroDivisionError: float division by zero

In [71]:
dividend = input("Dividend: ")
divisor = input("Divisor: ") 
try:
    print(float(dividend) / float(divisor))    
except ZeroDivisionError as detail: 
    print("ZeroDvisionError", detail)

Dividend: qooo
Divisor: 3


ValueError: could not convert string to float: 'qooo'

In [73]:
dividend = input("Dividend: ")
divisor = input("Divisor: ") 
try:
    print(float(dividend) / float(divisor))    
except ZeroDivisionError as detail: 
    print("ZeroDvisionError", detail)
except:
    print('error')

Dividend: qoo
Divisor: 3
error


In [74]:
dividend = input("Dividend: ")
divisor = input("Divisor: ") 
try:
    print(float(dividend) / float(divisor))    
except ZeroDivisionError as detail: 
    print("ZeroDvisionError", detail)
except:
    pass

Dividend: 3
Divisor: 0
ZeroDvisionError float division by zero


In [76]:
dividend = input("Dividend: ") 
divisor = input("Divisor: ")
try:
    print(float(dividend) / float(divisor))
except: 
    print("Error")
else:
    print('SUCCESS')
finally:
    print('final block')

Dividend: 3
Divisor: 5
0.6
SUCCESS
final block


## Class

In [77]:
class Sample(object):
    pass

x = Sample()

In [78]:
x

In [79]:
type(x)

__main__.Sample

### Attribute

In [80]:
class Dog(object):
    
    def __init__(self, breed):
        self.breed = breed

In [81]:
sam = Dog(breed = 'Lab')
frank = Dog(breed = 'Huskie')

In [82]:
sam.breed

'Lab'

In [83]:
frank.breed

'Huskie'

In [84]:
class Dog(object):
    species = 'mammal' # 類別屬性 
    
    def __init__(self,breed,name):
        self.breed = breed
        self.name  = name

In [85]:
sam = Dog(breed = 'Lab', name = 'Sam')
frank = Dog(breed = 'Huskie', name = 'Frank')

In [86]:
sam.breed

'Lab'

In [87]:
sam.name

'Sam'

In [88]:
frank.breed

'Huskie'

In [89]:
frank.name

'Frank'

In [90]:
frank.species

'mammal'

In [91]:
sam.species

'mammal'

In [92]:
Dog.species

'mammal'

### Method

In [93]:
class Circle(object):
    PI = 3.14
    def __init__(self, radius):
        self.radius = radius
    def area(self):
        return self.radius * self.radius * Circle.PI
    def getRadius(self):
        return self.radius
    def setRadius(self, radius):
        self.radius = radius

In [94]:
c1 = Circle(3)

In [95]:
c1.radius

3

In [96]:
c1.area()

28.26

In [97]:
c1.getRadius()

3

In [98]:
c1.PI

3.14

In [99]:
c1.setRadius(5)

In [100]:
c1.area()

78.5

## Module

In [101]:
import test

In [102]:
print(dir(test))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'hello', 'var']


In [103]:
test.var

'I am a variable'

In [104]:
test.hello('David')

Hello, David


In [106]:
#最安全的存取方式
import test
test.hello('david')

Hello, david


In [109]:
def hello(n):
    print(f'howdy, {n}')
hello('david')

howdy, david


In [110]:
#較不安全
from test import hello
hello('david')

Hello, david


In [111]:
#較不安全
from test import hello as h
h('david')

Hello, david


In [112]:
from test import * 
print(var)

I am a variable


## Package

In [1]:
import child

In [5]:
#較不安全
from child import test
test.hello('David')

Hello, David


In [9]:
#最安全的方式
import child
child.test.hello('david')

Hello, david


In [11]:
# 次不安全的方式
from child.test import hello
hello('david')

Hello, david


In [12]:
# 最不安全的方式
from child.test import *
hello('david')

Hello, david


## 真 對話機器人

In [28]:
! pip install pyAudio

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [13]:
! pip install SpeechRecognition

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [18]:
import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

print(r.recognize_google(audio,language='zh-TW'))


Say something!
我愛國泰人壽


In [15]:
?r.recognize_google

In [19]:
import speech_recognition as sr

def listenTo():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something!")
        audio = r.listen(source)

    return r.recognize_google(audio,language='zh-TW')


In [20]:
qa = {
  '我想買保單'  : '以下是我們推薦的保險商品',
  '我想申請理賠': '以下是專員電話',  
  '再見'       : '掰掰'  
}

In [21]:
qa.get(listenTo(), '我現在還不聰明，以後變聰明以後再告訴你')

Say something!


'以下是我們推薦的保險商品'

In [22]:
! pip install gTTS

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [27]:
from gtts import gTTS
tts = gTTS('九四八七九四狂',lang='zh-TW')
tts.save('hello.mp3')

In [25]:
?gTTS

In [29]:
! pip install pygame

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [32]:
import tempfile
from gtts import gTTS
from pygame import mixer

def speak(sentence):
    mixer.init()
    with tempfile.NamedTemporaryFile(delete=True) as fp:
        tts = gTTS(text=sentence, lang='zh-TW')
        tts.save("{}.mp3".format(fp.name))
        mixer.music.load('{}.mp3'.format(fp.name))
        mixer.music.play()

In [33]:
speak('昨天媽祖托夢給我')

In [34]:
qa = {
  '我想買保單'  : '以下是我們推薦的保險商品',
  '我想申請理賠': '以下是專員電話',  
  '再見'       : '掰掰'  
}

In [37]:
speak(qa.get(listenTo(), '我現在還不聰明，以後變聰明以後再告訴你'))

Say something!


In [40]:
import requests
from bs4 import BeautifulSoup
term = '長榮航空'
res = requests.get(f'https://zh.wikipedia.org/wiki/{term}')
soup =  BeautifulSoup(res.text, 'lxml')
soup.select_one('p').text

'長榮航空（英語譯名：EVA AIR，臺證所：2618）是一家臺灣航空公司，為長榮集團與星空聯盟成員，1991年開航，以桃園國際機場做為樞紐。其主要業務為經營國際客運及貨運航線[4]，成立之初亦提供國內航線服務，但在1998年後全面轉由同屬長榮集團的立榮航空負責。長榮航空在1992年開始提供豪華經濟艙服務，是全球第一家設立此種客機艙等的航空公司。長榮航空自西元2013年6月18日起成為星空聯盟成員之一。\n'

In [48]:
import requests
from bs4 import BeautifulSoup
term = '長榮航空'
def getKnowledge(term):
    res = requests.get(f'https://zh.wikipedia.org/wiki/{term}')
    soup =  BeautifulSoup(res.text, 'lxml')
    return soup.select_one('p').text

In [49]:
speak(getKnowledge(listenTo()))

Say something!


## 利用JIeba 做中文的 WordCount

In [50]:
! pip install jieba

You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [51]:
speech = '''
大會主席蘇嘉全院長，現場各位貴賓，電視機前面、以及網路上收看直播的全體國人同胞，大家早安，大家好！

今天是中華民國一百零七歲的生日，現場有許多來自全世界各地的僑胞和好朋友，跟我們一起歡度國家的慶典。我要代表臺灣人民，跟遠道而來的各位，致上最深的謝意。

在國慶的這一天，我們不只要共同慶祝，更要一起思考國家的未來。過去一年，新的國際局勢正在考驗著每一個國家，當然也考驗著我們。

政府無時無刻都在思考，如何從挑戰中發現機遇，如何在變動中，找出國家最佳戰略跟出路。今天我就要藉著這個機會，向全國人民完整說明政府的因應之道。

相信大家都觀察到，國際政經局勢正在面臨劇烈的變化。美中之間的貿易衝突，讓國際產業分工出現重組，也對原有的經貿秩序帶來衝擊。

在此同時，印太地區以及兩岸關係的複雜度，也相應升高。中國試圖挑戰區域現狀的作為，已經引起國際社會高度地關注。臺灣位處西太平洋第一線，自然承受巨大的壓力。

這段時間以來，中國單方面的文攻武嚇和外交打壓，不但傷害了兩岸關係，更嚴重挑戰了臺海和平穩定的現狀。

面對打壓，有些人希望政府採取更具對抗性的立場。不過，也有另一些人認為，我們應該要退讓妥協。

但是各位，越是劇烈的變局，臺灣就越要維持穩定，以沉著的態度化解壓力，冷靜地尋找生存的利基。

這是兩年多來我一貫的堅持。維護兩千三百萬人民自由民主的生活方式，捍衛中華民國的永續發展，維持臺海和平跟區域穩定，這是全體臺灣人民最大的公約數，每一個負責任的政治人物和政黨，都應該要堅持捍衛到底！

當全世界都在因應中國勢力擴張的同時，我所領導的政府要讓世界看見臺灣的強韌。捍衛臺灣的最佳方案，就是要讓臺灣在世界上變得不可或缺，也不可取代。

外在力量企圖單方面改變臺海現狀的做法，不可能被臺灣人民接受，任何違反普世價值的主張，也絕不會獲得國際社會的認同和支持。

我也要再一次呼籲北京當局，一個負責任的大國，應該在區域及全球，扮演良性的角色，而不是衝突的來源。

做為總統，我要向大家保證，我們不會貿然升高對抗，也不會屈從退讓。我不會因一時的激憤，走向衝突對抗，而讓兩岸關係陷入險境。我也不會背離民意，犧牲臺灣的主權。在變局當中，我們絕對不能錯估情勢。激化衝突或者妥協屈從，都只會治絲益棼。

我們的因應之道，就是「求穩、應變、進步」。這條路雖然充滿了挑戰，但卻是現階段臺灣必須穩健前行的道路。

有效的因應策略，植基於堅強的國力。所以當前最重要的任務，就是強化國家安全、強化經濟實力、強化社會安全網，不斷地「壯大臺灣」，厚植實力，提升臺灣在國際上的不可替代性，這才是臺灣永續生存的利基。

當前國家安全所面臨的挑戰，已經不僅僅是傳統國防軍事安全。外交施壓、社會滲透，甚至經濟安全，都是可能造成威脅的手段。當務之急，就是建構整體戰略，啟動國家安全強化的工程。

國家安全整體布局的第一個面向，就是在外交上強化價值連結，建構臺灣不可取代的戰略重要性。

臺灣擁有重要的地緣戰略地位，面對國際變局，我們的戰略選擇相當清楚，就是要堅守自由民主以及市場經濟。這兩項根本價值，是臺灣今天成為亞洲民主典範，及發展經濟實力的重要基礎。

過去兩年，在中國的壓力之下，我們堅持價值理念，展現高度韌性，讓越來越多理念相近國家，表達對中華民國臺灣的支持。

尤其是美國，最近不僅國會通過了許多友臺法案，日前彭斯副總統，也公開譴責中國打壓臺灣外交，並且肯定臺灣的民主制度。

和臺灣共享民主價值的日本，無論是在國際場合的聲援、或是天災時相互協助關懷，都讓兩國間的友誼越發密切。

前陣子，歐洲議會也通過決議，肯定臺灣民主發展，同時也呼籲歐盟國家全力遏止中國武力挑釁臺灣、破壞臺海和平。

我們也有很多友邦，積極為臺灣奔走，呼籲國際合作不該遺漏臺灣。今天，三位為臺灣仗義執言的好朋友，巴拉圭的阿布鐸總統閣下、聖克里斯多福及尼維斯的席頓總督閣下，以及聖露西亞的查士納總理閣下，也出席了我們的國慶典禮。

讓我們藉著這個機會，向他們表達最誠摯的感謝。現在請大家用熱情的掌聲，歡迎這三位遠道而來的貴賓。

國家安全整體布局的第二個面向，就是提升國防戰力。

「重層嚇阻，防衛固守」，是我們的軍事戰略。它的核心價值，就在提升中華民國國軍的戰力。我曾經說過，只要蔡英文任總統的一天，國防預算每年都會穩定成長。我們精實的部隊和戰備，絕對有能力捍衛中華民國臺灣的主權！

此外，我們也全力強化「國防自主」的能力。今年六月，我到漢翔公司，主持高教機的開架典禮，今年八月，我也在海軍司令部宣布「新海軍啟航」。

重啟延宕多時的高教機國造和潛艦國造計畫，將引領國防工業邁向新時代。未來的國防工業，不只能夠強化國軍戰力，更能夠透過帶動產業升級跟群聚，成為經濟發展的重要動力。

國家安全布局的第三個面向，是阻止外來勢力對國內進行滲透破壞，確保民主制度及社會經濟正常運作。

臺灣的多元民主，是我們堅決守護的價值。但是如果有其他國家，利用臺灣社會的自由，來進行滲透、製造亂象，我們一定會用盡一切方式來防範，絕對不會坐視。

無論是製造散布假消息、非法竊取科技情報，還是蓄意破壞資訊安全系統，甚至企圖用各種方式介入選舉、干擾政治運作的行為，只要罪證確鑿，我們一定嚴辦到底。

針對系統性、來自特定國家背景的假消息傳播，我們也會加強跨國合作。不僅僅是交流經驗，未來更要建立查核和通報機制，共同來因應這些假消息對各國的社會穩定，所帶來的破壞和衝擊。

國家安全整體布局的第四個面向，就是全球經貿戰略的重整及全新布局。

面對美中貿易衝突，和全球經貿秩序重建的巨大變局，我們必須調整臺灣在區域發展及全球供應鏈的角色。我們要以中、大型臺商在區域分工的整合能力及全球布局能量，加上中小企業的活力，來開展全新的戰略布局，催化臺灣經濟全面轉型升級。

我們要做三件重要的事情：

第一，從產業結構及資源互補的角度，在研發及尖端製造領域，和美、歐、日等工業先進國家，建立緊密的產業分工及技術連結，創造全新、高效率的供應鏈。

第二，從資源及市場共享的角度，在具發展潛力的新南向國家及其他新興市場，透過多元合作，共同打造攸關經濟發展及民生福祉的關鍵產業鏈，促進經濟的共榮發展。

第三，在我們的邦交國，協同當地政府共同面對氣候變遷的挑戰及尋找新的發展機會，打下經濟永續發展的基礎，也為臺灣開闢未來的新市場、新生產基地、以及全球布局的新據點。

在經濟實力的強化上，我們必須要強力的推動經濟轉型，有效率的執行基礎建設計畫，認真解決五缺問題，並將經濟成長的利益，由全民共享。

經濟轉型的關鍵在科技。政府正努力朝「系統導向、軟硬整合、軍民合一，以及國際鏈結」四大目標，快速提升科技水準及研發的能量，以作為經濟提升的重要基礎。

我們用新的思維，拆解不合時宜的框架，也鬆綁了阻礙競爭的約束，帶領產業走向新的機遇。

在這當中，「5加2產業創新計畫」已經有效驅動產業升級轉型。導入智慧製造的機械產業，去年的產值已經突破一兆元，精密度跟附加價值也更上一層樓，帶動了航太、物聯網，以及醫材的製造水準。

另外，「非核家園」的目標也確立了綠能發展的藍圖，並吸引國際離岸風電大廠前來投資。連帶地，新的風電產業鏈，也正在逐漸形成。

我們也要強化多元的國際布局，產業才有能力在面對變局時，快速調整供應鏈來因應。

行政院已經組成專案小組，協助臺商多元布局生產基地。願意回臺灣投資的臺商，我們鼎力相助，如果希望到其他國家投資布局，我們也會全力支援。

今年，「前瞻基礎建設」計畫第一期特別預算已經開始執行，建設的效益會逐漸展現，對擴大內需的貢獻也在發酵當中。這當中的綠能、數位、水資源、軌道、城鄉，是下一階段臺灣要優先投資的基礎建設。

在彰化，透過綠電稅收，政府有了穩定的財政基礎，可以確保學生營養午餐、社會福利實施的財政平衡。

在原鄉部落及偏遠地區，我們鋪設了寬頻建設，讓小朋友透過網路跟世界連結，拉近城鄉的差距。

在水資源建設上，透過石門水庫中庄調整池、湖山水庫下游自來水工程、曾文水庫防淤隧道的興建，我們穩定了從北到南的供水。

因為極端氣候強降雨所造成的局部地區淹水問題，也正透過各地滯洪池、人工湖、河川整治和下水道清淤等工程，希望做到快速減災的效果。

在交通建設方面，東部地區，透過蘇花公路改善計畫、南迴公路改善計畫，已經初步看見成果。

大家所關心的軌道建設，我們也加緊努力，強化進入東部地區的鐵路系統，以及花東之間的鐵路系統，讓環島的鐵路系統更加完備。

連結北部都會地區的基隆輕軌、新竹輕軌，串連中部區域的臺中山手線，以及捷運綠線延伸彰化方案，還有高雄捷運紅線延伸、黃線新建案等，從南到北，許多新建計畫都已經展開規劃，並陸續進入核定階段。

軌道建設的發展，不僅提供便捷的交通，更能有效減少汽機車造成的空氣污染。

大力推動前瞻基礎建設的目的，就是要改善投資環境、均衡區域發展，為臺灣的下一個世代創造更優質的環境和生活。

我們致力改善產業的投資環境。企業所關切的生產元素，包括土地、水、電、人才、勞工的五缺問題，在賴院長「做實事」的態度下，一項又一項逐步解決。

請大家回憶一下，去年夏天，能源供應十分緊張，供電警戒的橘燈一共亮起六十六天。今年夏天，無論天氣和景氣，都比去年熱，但是供電警戒的橘燈一天也沒有亮過，我們度過了供電危機。

我們再回憶一下，今年上半年，西部地區降雨很少，大家都擔心缺水。但是透過開源、節流、調度和備援的措施，再加上前瞻基礎建設計畫，我們也安然度過了挑戰。

前陣子，台積電、華邦電、力晶等大廠，都加碼投資臺灣。國際大公司Google、微軟、思科、Facebook，有些準備在臺灣設置研發中心，有些是提出新的合作計畫，這些代表了我們改善投資環境的成果，得到了國內外廠商的肯定。

當經濟結構轉型的工程啟動，基礎建設開始興建，投資環境呈現改善的同時，我們看見景氣復甦，臺灣經濟也開始穩健成長。

兩年前，我們走出了連續三季的衰退；今年一到五月的失業率，是十八年來同期新低。2017年實質總薪資更創歷史新高，結束了薪資倒退十幾年的窘境。

經濟指標變好，當然令人欣喜，但是對政府來說，最重要的事情是，怎麼將經濟成長的紅利，分享給所有人民。

今年，我們把軍公教調高薪資百分之三，帶動了企業加薪的風潮。我們也加速調漲基本工資，明年起將達到兩萬三千一百元，終於擺脫了22K。此外，我們也為學貸增加了四年的寬緩期，減輕學貸族的負擔。

明年起生效的租稅改革方案，優化稅制也兼顧租稅公平，大幅調高四大扣除額，未來月薪三萬元以下的民眾，就不需要繳個人所得稅。有學齡前兒童的家庭，免稅額也大大提高。

在健全社會安全體系方面，2016年，我剛剛就任時，大家最憂慮的就是，房價太高、長輩沒有人照顧、育兒負擔沉重、社會治安不佳、毒品氾濫動搖國本等問題。整個國家的社會安全體系，可以說是百廢待舉。因此這兩年來，我們幾乎是用急行軍的速度，來健全社會安全體系。

攸關居住正義問題的社會住宅，透過多元興辦，目前完工和正在興辦中的，已經超過兩萬四千戶。加上後續開工的案件，今年年底總戶數將可達到近三萬五千戶。在問題最嚴峻的雙北市，近兩年已經有超過五千四百戶陸續入住，我也去視察了其中幾個，無論是質或量，都令人滿意。

民眾迫切需要的長照服務，現在升級成「長照2.0」，只要打1966長照專線，就有專人來協助。我們擴大了服務對象和範圍；我們也提高了待遇，使得更多人投入長照服務，增加了服務供給，讓更多家庭的需求被滿足。因為這些努力，接受長照服務人數，在最近一年增加超過五成。而接受喘息服務人數，最近一年則增加了一倍。

生育率低，已經成為國安問題。我們除了提供津貼，更透過「準公共化系統」的建置，朝公共化教保的目標邁進了一步。目前，準公共化和公共化托育，共可提供平價收托量達到五萬六千人，比過去更加普及。我們的目標很清楚，減輕家長的負擔，生育率就有機會改善。

大家所關心的治安問題，我們透過科技協助，智慧部署警力，犯罪發生數確實呈現下降趨勢。我們也對組織犯罪和詐騙進行全面掃蕩，今年到現在，檢警依違反新修正的《組織犯罪防制條例》，積極打擊包括詐騙集團、幫派在內的各類犯罪組織，起訴超過一千三百人。

今年二月和六月兩波「安居緝毒方案」，查獲各級毒品高達九千七百公斤，所逮捕的製毒者、販毒者和藥頭，加起來超過一千九百人。我們更在四年內投入一百億的經費，執行「新世紀反毒策略」，將毒品網絡從社會連根拔起。

各位國人同胞，國家發展的方向已經在改變。改變並不可怕，因為改變是為了因應世界的變化，讓臺灣能夠繼續屹立不搖。

改變也是為了改正過去的錯誤，讓我們把國家交給下一代的時候，不會再有難以承擔的包袱。所以這兩年多來，我們全力衝刺國政的改革。國家要進步，就不能走回頭路。

年金改革我們不能走回頭路。因為我們不能讓每一個世代都陷入財務危機的懸崖邊緣。

非核家園也不能走回頭路。這不只是為了核電廠所在的新北和屏東，更是為了世世代代的臺灣人，能免於核災的威脅。

轉型正義更不能走回頭路。過去執政者犯的錯誤，現在的政府更要勇敢面對，透過釐清真相，記取教訓，民主才會向前跨大步。

改革也許有陣痛，但是在十年、二十年之後，下一代會感到也會感謝我們此刻的選擇。這是考驗領導人意志的時刻，我會把這個重擔扛起來，帶領國家往正確的方向走。

在最後，我要特別感謝今天的國歌領唱代表，他們是一群「燈塔守護者」。

我們全國各地的海岸，有三十六座燈塔。有一群人，負責守護著燈塔，維護海上航行的安全。我要代表國家，感謝各位忍受著孤獨和艱難，照亮海岸。

臺灣就是一個燈塔。我們的民主轉型，不僅照亮了自己曾經走過的黑暗，也為所有追求民主的人們，提供了暗夜中的光芒。所以，在香港、在中國大陸，以及在世界上各個角落，追求民主的朋友，請往臺灣的方向看過來。臺灣的民主，會照亮世界！

當世界看見臺灣的美好，臺灣就不會孤獨。我要告訴國際友人，這條路，我們會勇敢堅定地走下去！

臺灣的民主也許吵吵鬧鬧，但我們一向因臺灣而團結，因團結而堅強。因為這個國家，屬於兩千三百萬人民，這個國家，要完整地傳給世世代代！

我們始終相信，臺灣人能用獨特的堅韌，面對從來不曾停止過的內外挑戰，團結起來，讓國家更好，這就是今年國慶的主題，「臺灣共好」的最佳寫照。最後，我要祝大家身體健康，萬事如意，中華民國生日快樂。謝謝，謝謝大家！

'''

In [53]:
import jieba
dic = {}
for word in list(jieba.cut(speech)):
    dic[word] = dic.get(word, 0) + 1 
swd = sorted(dic.items(), key= lambda k: k[1], reverse=True)

In [58]:
for k, v in swd[0:30]:
    if len(k) >= 2:
        print(k, v)

我們 59
臺灣 46
國家 27
經濟 19
國際 14
社會 14
民主 14
發展 14


In [60]:
from collections import Counter
c = Counter(list(jieba.cut(speech)))
for k, v in c.most_common(50):
    if len(k) >= 2:
        print(k,v )

我們 59
臺灣 46
國家 27
經濟 19
國際 14
社會 14
民主 14
發展 14
安全 14
大家 12
產業 12
已經 12
就是 12
透過 12
建設 12
布局 11
今年 11
以及 10
強化 10
基礎 10
政府 9
計畫 9
投資 9


In [64]:
try:
    f = open('testfile','r') 
    f.write('Test write this')
except Exception as e:
    print(e)
f.close()

not writable


## Pandas

In [1]:
import pandas as pd
link = 'https://raw.githubusercontent.com/ywchiu/cathaylifepy/master/data/rent591.xlsx' 
df   = pd.read_excel(link, index_col=0)

In [3]:
#df

In [5]:
df2 = pd.read_clipboard()
df2.head(3)

0
0  1
1  2
2  3

In [6]:
df.head()

address  floor  allfloor  layout  area    price  browsenum_all  \
0  復興南路160巷精華地段雙..      2        15  2房1廳1衛  28.0   43,800           2180   
1  臥龍街前眺101後擁山景,..     11        12  3房2廳2衛  69.0  120,000           1722   
2   光復南路高樓層大巨蛋正對..     10        13  4房2廳2衛  71.3  130,000           3272   
3   信義路三段台北大安森林公..     12        14  1房2廳1衛  11.0   36,000           4890   
4      和平東路一段和平大..      4        11  2房2廳1衛  16.0   30,000           4900   

  created_date  
0   2019/06/05  
1   2019/06/05  
2   2016/12/14  
3   2019/02/26  
4   2019/06/04

In [8]:
df.head().to_clipboard()

## 資料清理

In [9]:
a=  [1,2,3,4,5]
a.append(6)
a

[1, 2, 3, 4, 5, 6]

In [10]:
sum(a)

21

In [11]:
a.append('qoo')
a

[1, 2, 3, 4, 5, 6, 'qoo']

In [12]:
sum(a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [13]:
a = [1, 3, 5, 7, 9]
b = [2, 4, 6, 8, 10]

In [14]:
len(a)

5

In [15]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [16]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [17]:
ary = []
for i in range(len(a)):
    ary.append(a[i] + b[i])
ary

[3, 7, 11, 15, 19]

In [18]:
[a[i] + b[i] for i in range(len(a))]

[3, 7, 11, 15, 19]

### ZIP

In [20]:
for ele in zip(a,b):
    print(ele)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [21]:
for ele in zip(a,b):
    print(ele[0] + ele[1])

3
7
11
15
19


In [22]:
[ele[0] + ele[1] for ele in zip(a,b)]

[3, 7, 11, 15, 19]

In [23]:
type(a)

list

In [24]:
import numpy as np
na = np.array(a)
nb = np.array(b)

In [25]:
type(na)

numpy.ndarray

In [26]:
print(dir(a))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [27]:
print(dir(na))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [28]:
a

[1, 3, 5, 7, 9]

In [29]:
na

array([1, 3, 5, 7, 9])

In [30]:
c = [1,2,3, 'qoo']
nc = np.array(c)

In [31]:
c

[1, 2, 3, 'qoo']

In [32]:
nc

array(['1', '2', '3', 'qoo'], dtype='<U21')

In [33]:
na

array([1, 3, 5, 7, 9])

In [34]:
nb

array([ 2,  4,  6,  8, 10])

In [35]:
na + nb

array([ 3,  7, 11, 15, 19])

In [36]:
na * nb

array([ 2, 12, 30, 56, 90])

In [37]:
np.sqrt(na * nb)

array([1.41421356, 3.46410162, 5.47722558, 7.48331477, 9.48683298])

In [40]:
naa = np.array([[90,87],[73,65]])
naa

array([[90, 87],
       [73, 65]])

In [45]:
weight = np.array([[0.6],[0.4]])
weight

array([[0.6],
       [0.4]])

In [46]:
np.dot(naa, weight)

array([[88.8],
       [69.8]])

In [47]:
na = np.array([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35],
['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])

In [48]:
na

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [49]:
na[:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U5')

In [51]:
na[:,2].astype(int).sum()

161

In [54]:
import numpy as np
na = np.array([['name', 'gender', 'age'], ['frank', 'M', 29], ['mary', 'F',23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]]) 
na

array([['name', 'gender', 'age'],
       ['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U6')

In [61]:
na[1:,na[0,:] == 'age'].flatten().astype(int).sum()

161

In [62]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
0    6 non-null object
1    6 non-null object
2    6 non-null int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [64]:
df.columns = ['name', 'gender', 'age']

In [65]:
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [67]:
#  select sum(age) from df
df['age'].sum()

161

In [68]:
df['age'].mean()

26.833333333333332